CREATE TABLE ACTIVITY (

	id NUMBER GENERATED ALWAYS AS IDENTITY,
	
	DESCRIPTION VARCHAR2(4000),
	
	PRIMARY KEY(id));

INSERT INTO ACTIVITY (DESCRIPTION) VALUES('Submit a job application');

COMMIT;

SELECT DESCRIPTION FROM ACTIVITY;