CREATE TABLE CONDITION (

	id NUMBER GENERATED ALWAYS AS IDENTITY,
	
	DESCRIPTION VARCHAR2(4000),
	
	PRIMARY KEY(id));

INSERT INTO CONDITION (DESCRIPTION) VALUES('I get a job');

COMMIT;

SELECT DESCRIPTION FROM CONDITION;
