CREATE TABLE TIMEUNIT (

	id NUMBER GENERATED ALWAYS AS IDENTITY,
	
	DESCRIPTION VARCHAR2(4000),
	
	PRIMARY KEY(id));

INSERT INTO TIMEUNIT (DESCRIPTION) VALUES('Hour');

COMMIT;

SELECT * FROM TIMEUNIT;
