CREATE TABLE ITERATION (

	id NUMBER GENERATED ALWAYS AS IDENTITY,
	
	ITERCOUNT NUMBER,

	TIMEUNITCOUNT NUMBER,

	TIMEUNITid NUMBER,

    CONSTRAINT ITERATIONpk PRIMARY KEY (id),

    CONSTRAINT fkTIMEUNIT
		FOREIGN KEY (TIMEUNITid)
		REFERENCES TIMEUNIT(id)
	
	);

INSERT INTO ITERATION (ITERCOUNT, TIMEUNITCOUNT, TIMEUNITid) VALUES(1, 24, 1);

COMMIT;

SELECT * FROM ITERATION;
