CREATE TABLE ALGORITHM (

	id NUMBER GENERATED ALWAYS AS IDENTITY,
	
	ACTIVITYid NUMBER,

	ITERATIONid NUMBER,

	CONDITIONid NUMBER,

    CONSTRAINT ALGORITHMpk PRIMARY KEY (id),

    CONSTRAINT fkACTIVITY
		FOREIGN KEY (ACTIVITYid)
		REFERENCES ACTIVITY(id),

    CONSTRAINT fkITERATION
		FOREIGN KEY (ITERATIONid)
		REFERENCES ITERATION(id),

    CONSTRAINT fkCONDITION
		FOREIGN KEY (CONDITIONid)
		REFERENCES CONDITION(id)
	
	);

INSERT INTO ALGORITHM (ACTIVITYid, ITERATIONid, CONDITIONid) VALUES(1, 1, 1);

COMMIT;

SELECT * FROM ALGORITHM;
